### ISSUE TITLE
看似很牛X，怎么没有 readme 啊

### ISSUE THREAD

**Issue by justjavac** [xinyu198736/js2image#1]

**Comment by small-tou** [comment]
还有bug，刚提交上来。。。readme已补充，还有bug额

**Comment by justjavac** [comment]
为什么不是image2js？

**Comment by justjavac** [comment]
你做的这个，我在4年前，大概是2011年吧，已经做过了。用来生成我博客的about页。

**Comment by small-tou** [comment]
不是一类东西吧。

**Comment by small-tou** [comment]
两个要点，把js代码根据一张图片格式化成任意ascii字符画，并且可以继续在浏览器里运行。

**Comment by small-tou** [comment]
感觉我应该改个名字叫 js2image ...

**Comment by justjavac** [comment]
当时用 python 写的，把我的名字“迷渡”转换成javascript代码，然后可以在浏览器正常运行。

![image](https://cloud.githubusercontent.com/assets/359395/11969291/8599b5de-a952-11e5-9229-ae23e3aeb63b.png)

**Comment by small-tou** [comment]
我这个可以保留原来代码的格式，而且可以编译任意的js代码，感觉还是有点用的，啦啦啦啦

**Comment by justjavac** [comment]
很 geeeeeeeeeeeeeeeeeeeeeeeeeeeek
