### ISSUE TITLE
index.汉.js 是最骚的

### ISSUE THREAD

**Issue by Rookiewan** [xinyu198736/js2image#16]
index.汉.js 是最骚的
![](https://i.loli.net/2018/04/04/5ac43610c0fd9.jpg)

**Comment by small-tou** [comment]
这个是用我另一个库自动翻译出来的，不小心放在这里了。。。
https://github.com/xinyu198736/hancode

**Comment by WangJiangJiaoZi** [comment]
这个很有意思
