### ISSUE TITLE
跑不通，报错了！

### ISSUE THREAD

**Issue by kyo4311** [xinyu198736/js2image#4]
[Error: Could not execute GraphicsMagick/ImageMagick: gm "identify" "-ping" "-
rmat" "%wx%h" "C:\Users\KYO\AppData\Roaming\npm\node_modules\js2image\resource
ree.png" this most likely means the gm/convert binaries can't be found]
C:\Users\KYO\AppData\Roaming\npm\node_modules\js2image\utils\image-to-struct.j
16
var content = converted.replace(/\S[0m/g,"").replace(/\n/g,"\",\n\"");

**Comment by small-tou** [comment]
看文档，依赖GraphicsMagick模块
