### ISSUE TITLE
ImageMagick err

### ISSUE THREAD

**Issue by wangmingquan** [xinyu198736/js2image#8]
[Error: Could not execute GraphicsMagick/ImageMagick: gm "identify" "-ping" "-format" "%wx%h" "./headp.png" this most likely means the gm/convert binaries can't be found]
/Users/xxx/node_modules/js2image/utils/image-to-struct.js:19
      var content = converted.replace(/\S[0m/g,"").replace(/\n/g,"\",\n\"");

**Comment by small-tou** [comment]
没有安装 GraphicsMagick 依赖
