### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by bumaociyuan** [xinyu198736/js2image#9]
```
onverting ./resource/release.js
[Error: Could not execute GraphicsMagick/ImageMagick: gm "identify" "-ping" "-format" "%wx%h" "/usr/local/lib/node_modules/js2image/resource/tree.png" this most likely means the gm/convert binaries can't be found]
/usr/local/lib/node_modules/js2image/utils/image-to-struct.js:19
      var content = converted.replace(/\S\[0m/g,"").replace(/\n/g,"\",\n\"");
                             ^

TypeError: Cannot read property 'replace' of undefined
```

`TypeError: Cannot read property 'replace' of undefined`
README 需要更新

```
npm install -g replace
```

**Comment by small-tou** [comment]
不是这个问题引起的，看起来是没有安装GraphicsMagick依赖造成的，可以看下文档如何安装

**Comment by bumaociyuan** [comment]
装了GraphicsMagick 依然报这个

2015-12-24 16:29 GMT+08:00 芋头 notifications@github.com:

**Comment by small-tou** [comment]
this most likely means the gm/convert binaries can't be found 

应该是装失败了。是什么系统？

**Comment by bumaociyuan** [comment]
macos 10.11.1

npm install -g replace 装了就可以用了

**Comment by RainCha** [comment]
windows 10 系统，我也遇到了这个问题，首先，下载并安装了graphicsmagick.exe, 然后，npm install -g replace  ,然后就可以了。

**Comment by bumaociyuan** [comment]
@RainCha  所以要更新 readme 啊

2015-12-24 21:40 GMT+08:00 RainCha notifications@github.com:

**Comment by RainCha** [comment]
是的，作者赶紧更新啊。

**Comment by small-tou** [comment]
npm install -g replace 

我没太理解是为什么需要这个。。。

**Comment by bumaociyuan** [comment]
![a22860dc-23cb-47f0-9319-edbde31f780e](https://cloud.githubusercontent.com/assets/4977911/11995365/81725950-aa8a-11e5-81a0-0fa4a98a404d.png)

**Comment by RainCha** [comment]
刚刚看了image-to-struct.js，npm install -g replace 这个应该是不需要的，但是觉得readme,还是需要强调一下windows系统的情况。

**Comment by small-tou** [comment]
恩，那我先备注下

**Comment by small-tou** [comment]
已加到readme，感谢大家
